export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const TASK_LIST_FAILURE = 'TASK_LIST_FAILURE'
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST'

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAILURE = 'TASK_CREATE_FAILURE'

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST'
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS'
export const TASK_DETAILS_FAILURE = 'TASK_DETAILS_FAILURE'

export const TASK_DETAILS_UPDATE_REQUEST = 'TASK_DETAILS_UPDATE_REQUEST'
export const TASK_DETAILS_UPDATE_SUCCESS = 'TASK_DETAILS_UPDATE_SUCCESS'
export const TASK_DETAILS_UPDATE_FAILURE = 'TASK_DETAILS_UPDATE_FAILURE'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAILURE = 'TASK_DELETE_FAILURE'

export const RESET_STATE = 'RESET_STATE';